module.exports = {
  key: 'page2',
  name: 'Hunt Page 2 - Curse of Maud',
  description:
    'The vampire Maud has started a campaign of terror in the city of Dax. Grab your holy water and get to work!',
  finalBoss: 'vampire-vampire',
  hunts: [
    {
      id: 6,
      key: 'hunt6',
      name: 'Bandit Captain',
      description: `Track down the bandits to first find Maud's secret identity.`,
      energyCost: 1,
      totalBattles: 6,
      battles: [
        { type: 'normal', monsterIndex: 'nightmare', difficulty: 'hard', goldReward: 43 }, // 102
        { type: 'normal', cr: 2, difficulty: 'medium', goldReward: 45 },
        { type: 'normal', cr: 2, difficulty: 'medium', goldReward: 47 },
        { type: 'normal', cr: 1, difficulty: 'hard', goldReward: 49 },
        { type: 'normal', cr: 1, difficulty: 'hard', goldReward: 51 },
        {
          type: 'mini-boss',
          monsterIndex: 'bandit-captain',
          difficulty: 'boss-strong', // 97
          firstGoldReward: 750,
          goldReward: 55,
        },
      ],
      unlocks: 'hunt7',
    },
    {
      id: 7,
      key: 'hunt7',
      name: 'Gibbering Mouther',
      description: `The bandit's led you into a trap. Watch out! `,
      energyCost: 1,
      totalBattles: 6,
      battles: [
        { type: 'normal', cr: 1, difficulty: 'hard', goldReward: 44 },
        { type: 'normal', cr: 2, difficulty: 'medium', goldReward: 46 },
        { type: 'normal', cr: 2, difficulty: 'medium', goldReward: 48 },
        { type: 'normal', cr: 0.25, difficulty: 'very-hard', goldReward: 50 },
        { type: 'normal', cr: 2, difficulty: 'medium', goldReward: 52 },
        {
          type: 'mini-boss',
          monsterIndex: 'gibbering-mouther',
          difficulty: 'boss-full',
          firstGoldReward: 810,
          goldReward: 57,
        },
      ],
      unlocks: 'hunt8',
    },
    {
      id: 8,
      key: 'hunt8',
      name: 'Vampire Spawn',
      description: `Turn your luck around by finding one of the vampire's spawns in the harbor.`,
      energyCost: 1,
      totalBattles: 7,
      battles: [
        { type: 'normal', cr: 2, difficulty: 'medium', goldReward: 45 },
        { type: 'normal', cr: 3, difficulty: 'medium', goldReward: 47 },
        { type: 'normal', cr: 3, difficulty: 'medium', goldReward: 49 },
        { type: 'normal', cr: 3, difficulty: 'medium', goldReward: 51 },
        { type: 'normal', cr: 3, difficulty: 'hard', goldReward: 52 },
        { type: 'normal', cr: 4, difficulty: 'medium', goldReward: 53 },
        {
          type: 'mini-boss',
          monsterIndex: 'vampire-spawn',
          difficulty: 'boss-full',
          firstGoldReward: 870,
          goldReward: 59,
        },
      ],
      unlocks: 'hunt9',
    },
    {
      id: 9,
      key: 'hunt9',
      name: 'Deva',
      description:
        'The heavens have come to test your valor.',
      energyCost: 2,
      totalBattles: 9,
      battles: [
        { type: 'normal', cr: 3, difficulty: 'medium', goldReward: 46 },
        { type: 'normal', cr: 3, difficulty: 'medium', goldReward: 47 },
        { type: 'normal', cr: 4, difficulty: 'medium', goldReward: 48 },
        { type: 'normal', cr: 4, difficulty: 'medium', goldReward: 49 },
        { type: 'normal', cr: 5, difficulty: 'medium', goldReward: 50 },
        { type: 'normal', cr: 6, difficulty: 'medium', goldReward: 49 },
        { type: 'normal', cr: 5, difficulty: 'medium', goldReward: 50 },
        { type: 'normal', cr: 5, difficulty: 'hard', goldReward: 52 },
        {
          type: 'mini-boss',
          monsterIndex: 'deva',
          difficulty: 'boss-full',
          firstGoldReward: 1180,
          goldReward: 60,
        },
      ],
      unlocks: 'hunt10',
    },
    {
      id: 10,
      key: 'hunt10',
      name: 'Chimera',
      description:
        `Evil grows around you, you're getting close.`,
      energyCost: 2,
      totalBattles: 8,
      battles: [
        { type: 'normal', cr: 5, difficulty: 'medium', goldReward: 47 },
        { type: 'normal', cr: 5, difficulty: 'medium', goldReward: 47 },
        { type: 'normal', cr: 6, difficulty: 'medium', goldReward: 49 },
        { type: 'normal', cr: 6, difficulty: 'medium', goldReward: 51 },
        { type: 'normal', cr: 6, difficulty: 'medium', goldReward: 51 },
        { type: 'normal', cr: 7, difficulty: 'medium', goldReward: 53 },
        { type: 'normal', cr: 7, difficulty: 'medium', goldReward: 55 },
        {
          type: 'mini-boss',
          monsterIndex: 'chimera',
          difficulty: 'boss-full',
          firstGoldReward: 930,
          goldReward: 70,
        },
      ],
      unlocks: 'hunt11',
    },
    {
      id: 11,
      key: 'hunt11',
      name: 'Gorgon',
      description:
        'Maud knows you hunt him and has unleashed the dreaded Gorgon to stop you!',
      energyCost: 2,
      totalBattles: 8,
      battles: [
        { type: 'normal', cr: 3, difficulty: 'very-hard', goldReward: 48 },
        { type: 'normal', cr: 4, difficulty: 'very-hard', goldReward: 50 },
        { type: 'normal', cr: 5, difficulty: 'medium', goldReward: 52 },
        { type: 'normal', cr: 5, difficulty: 'hard', goldReward: 54 },
        { type: 'normal', cr: 6, difficulty: 'medium', goldReward: 56 },
        { type: 'normal', cr: 8, difficulty: 'medium', goldReward: 54 },
        { type: 'normal', cr: 8, difficulty: 'very-hard', goldReward: 56 },
        {
          type: 'mini-boss',
          monsterIndex: 'gorgon',
          difficulty: 'boss-full',
          firstGoldReward: 970,
          goldReward: 75,
        },
      ],
      unlocks: 'hunt12',
    },
    {
      id: 12,
      key: 'hunt12',
      name: 'Vampire Lord Maud',
      description: `Finally, you've reached Maud's lair. Are you ready?`,
      energyCost: 2,
      totalBattles: 10,
      battles: [
        { type: 'normal', cr: 2, difficulty: 'very-hard', goldReward: 75 },
        { type: 'normal', cr: 4, difficulty: 'very-hard', goldReward: 77 },
        { type: 'normal', cr: 6, difficulty: 'hard', goldReward: 79 },
        { type: 'normal', cr: 8, difficulty: 'medium', goldReward: 81 },
        { type: 'normal', cr: 7, difficulty: 'medium', goldReward: 83 },
        { type: 'normal', cr: 8, difficulty: 'hard', goldReward: 85 },
        { type: 'normal', cr: 9, difficulty: 'medium', goldReward: 87 },
        { type: 'normal', cr: 11, difficulty: 'medium', goldReward: 89 },
        { type: 'normal', cr: 12, difficulty: 'hard', goldReward: 91 },
        {
          type: 'boss',
          monsterIndex: 'vampire-vampire',
          difficulty: 'boss-strong',
          firstGoldReward: 2253,
          goldReward: 93,
        },
      ],
      unlocksPage: 'finished',
    },
  ],
}
