module.exports = {
  key: 'page2',
  name: 'Hunt Page 2 - Wyrmling’s Trial',
  description: 'Oryzinax, a red dragon wyrmling, has made a lair in the mountains above Harvest Hill. You must strike it down while its still young.',
  finalBoss: 'red-dragon-wyrmling',
  hunts: [
    {
      key: 'hunt1',
      name: 'Darkmantle',
      description: 'This is page 2.',
      energyCost: 1,
      totalBattles: 3,
      battles: [
        { type: 'normal', cr: 0, difficulty: 'easy', goldReward: 24 },
        { type: 'normal', cr: 0, difficulty: 'easy', goldReward: 24 },
        { type: 'normal', cr: 0, difficulty: 'easy', goldReward: 24 },
        {
          type: 'mini-boss',
          cr: 0.25,
          monsterIndex: 'darkmantle',
          difficulty: 'boss-half',
          firstGoldReward: 700,
          goldReward: 28,
        },
      ],
      unlocks: 'hunt2',
    },
    {
      key: 'hunt2',
      name: 'Harpy',
      description: 'Take down the harpy by avoiding her song.',
      energyCost: 1,
      totalBattles: 5,
      battles: [
        { type: 'normal', cr: 0.25, difficulty: 'easy', goldReward: 26 },
        { type: 'normal', cr: 0.25, difficulty: 'easy', goldReward: 26 },
        { type: 'normal', cr: 0.5, difficulty: 'easy', goldReward: 28 },
        { type: 'normal', cr: 0.5, difficulty: 'easy', goldReward: 28 },
        {
          type: 'mini-boss',
          cr: 2,
          monsterIndex: 'harpy',
          difficulty: 'boss-half',
          firstGoldReward: 650,
          goldReward: 32,
        },
      ],
      unlocks: 'hunt3',
    },
    {
      key: 'hunt3',
      name: 'Rust Monster',
      description:
        'An army will be left unarmed if the rust monster is not hunted.',
      energyCost: 1,
      totalBattles: 8,
      battles: [
        { type: 'normal', cr: 0.25, difficulty: 'medium', goldReward: 48 },
        { type: 'normal', cr: 0.25, difficulty: 'medium', goldReward: 48 },
        { type: 'normal', cr: 0.5, difficulty: 'medium', goldReward: 50 },
        { type: 'normal', cr: 0.5, difficulty: 'medium', goldReward: 50 },
        { type: 'normal', cr: 1, difficulty: 'medium', goldReward: 50 },
        { type: 'normal', cr: 1, difficulty: 'medium', goldReward: 52 },
        {
          type: 'mini-boss',
          cr: 2,
          monsterIndex: 'rust-monster',
          difficulty: 'boss-full',
          firstGoldReward: 980,
          goldReward: 52,
        },
      ],
      unlocks: 'hunt4',
    },
    {
      key: 'hunt4',
      name: 'Sea Hag',
      description:
        'Kill the sea hag before more fall under her drowned man curse!',
      energyCost: 1,
      totalBattles: 10,
      battles: [
        { type: 'normal', cr: 0.25, difficulty: 'medium', goldReward: 48 },
        { type: 'normal', cr: 0.25, difficulty: 'medium', goldReward: 48 },
        { type: 'normal', cr: 0.25, difficulty: 'medium', goldReward: 48 },
        { type: 'normal', cr: 0.5, difficulty: 'medium', goldReward: 50 },
        { type: 'normal', cr: 0.5, difficulty: 'medium', goldReward: 50 },
        { type: 'normal', cr: 0.5, difficulty: 'medium', goldReward: 50 },
        { type: 'normal', cr: 1, difficulty: 'medium', goldReward: 52 },
        { type: 'normal', cr: 1, difficulty: 'medium', goldReward: 52 },
        {
          type: 'mini-boss',
          cr: 2,
          monsterIndex: 'sea-hag',
          difficulty: 'boss-full',
          firstGoldReward: 1080,
          goldReward: 52,
        },
      ],
      unlocks: 'hunt5',
    },
    {
      key: 'hunt5',
      name: 'Red Dragon Wyrmling (Boss)',
      description: 'Face the Red Dragon Wyrmling to prove your worth!',
      energyCost: 1,
      totalBattles: 10,
      battles: [
        { type: 'normal', cr: 0.25, difficulty: 'medium', goldReward: 48 },
        { type: 'normal', cr: 0.25, difficulty: 'medium', goldReward: 48 },
        { type: 'normal', cr: 0.25, difficulty: 'medium', goldReward: 48 },
        { type: 'normal', cr: 0.25, difficulty: 'medium', goldReward: 48 },
        { type: 'normal', cr: 0.5, difficulty: 'medium', goldReward: 56 },
        { type: 'normal', cr: 0.5, difficulty: 'medium', goldReward: 56 },
        { type: 'normal', cr: 1, difficulty: 'medium', goldReward: 58 },
        { type: 'normal', cr: 1, difficulty: 'medium', goldReward: 58 },
        { type: 'normal', cr: 1, difficulty: 'medium', goldReward: 58 },
        { type: 'normal', cr: 1, difficulty: 'medium', goldReward: 58 },
        {
          type: 'mini-boss',
          cr: 4,
          monsterIndex: 'red-dragon-wyrmling',
          difficulty: 'boss-strong',
          firstGoldReward: 1540,
          goldReward: 75,
        },
      ],
      unlocksPage: 'page2',
    },
  ],
}
