// shopMonsters.js

const allowedMonstersByPack = {
  starter: new Set([
    'darkmantle',
    'dryad',
    'ghoul',
  ]),
  common: new Set([
    'darkmantle',
    'dryad',
    'ghoul',
    'violet-fungus',
    'dust-mephit',
    'gelatinous-cube',
    'azer',
    'ettercap',
    'gibbering-mouther',
    'wight',
    'phase-spider',
    'ettin',
    'lamia',
    'ghost',
    'couatl',
  ]),
  uncommon: new Set([
    'roper',
    'salamander',
    'wraith',
    'hill-giant',
    'unicorn',
    'otyugh',
    'shambling-mound',
    'gorgon',
    'medusa',
    'chimera',
    'mammoth',
    'invisible-stalker',
    'drider',
    'oni',
    'treant',
    'vampire-spawn',
    'shield-guardian',
    'giant-ape',
    'bulette',
    'tyrannosaurus-rex',
  ]),
  rare: new Set([
    'djinni',
    'efreeti',
    'black-pudding',
    'wererat-hybrid',
    'werewolf-hybrid',
    'wereboar-hybrid',
    'weretiger-hybrid',
    'werebear-hybrid',
    'gynosphinx',
    'remorhaz',
    'hydra',
    'roc',
    'behir',
    'archmage',
    'storm-giant',
    'vampire-bat',
    'vampire-mist',
    'vampire-vampire',
    'mummy-lord',
    'purple-worm',
  ]),
  elemental: new Set([
    'air-elemental',
    'earth-elemental',
    'fire-elemental',
    'salamander',
    'gargoyle',
    'water-elemental',
    'xorn',
    'invisible-stalker',
    'djinni',
    'efreeti'
  ]),
}

module.exports = { allowedMonstersByPack }
