// shopMonsters.js

const allowedMonstersByPack = {
  starter: new Set([
    { monster: 'darkmantle'},
    { monster: 'dryad'},
    { monster: 'ghoul'},
  ]),
  common: new Set([
    { monster: 'darkmantle'},
    { monster: 'dryad'},
    { monster: 'ghoul'},
    { monster: 'violet-fungus'},
    { monster: 'dust-mephit'},
    { monster: 'gelatinous-cube'},
    { monster: 'azer'},
    { monster: 'ettercap'},
    { monster: 'gibbering-mouther'},
    { monster: 'wight'},
    { monster: 'phase-spider'},
    { monster: 'ettin'},
    { monster: 'lamia'},
    { monster: 'ghost'},
    { monster: 'couatl', chance: 0.02},
  ]),
  uncommon: new Set([
    { monster: 'roper'},
    { monster: 'salamander'},
    { monster: 'wraith'},
    { monster: 'hill-giant'},
    { monster: 'unicorn', chance: 0.01},
    { monster: 'otyugh'},
    { monster: 'shambling-mound'},
    { monster: 'gorgon'},
    { monster: 'medusa', chance: 0.05},
    { monster: 'chimera'},
    { monster: 'mammoth', chance: 0.05},
    { monster: 'invisible-stalker'},
    { monster: 'drider'},
    { monster: 'oni'},
    { monster: 'treant', chance: 0.01},
    { monster: 'vampire-spawn'},
    { monster: 'shield-guardian'},
    { monster: 'giant-ape', chance: 0.05},
    { monster: 'bulette'},
    { monster: 'tyrannosaurus-rex', chance: 0.03},
  ]),
  rare: new Set([
    { monster: 'djinni'},
    { monster: 'efreeti', chance: 0.02},
    { monster: 'black-pudding'},
    { monster: 'wererat-hybrid'},
    { monster: 'werewolf-hybrid'},
    { monster: 'wereboar-hybrid'},
    { monster: 'weretiger-hybrid'},
    { monster: 'werebear-hybrid', chance: 0.02},
    { monster: 'gynosphinx'},
    { monster: 'remorhaz'},
    { monster: 'hydra'},
    { monster: 'roc'},
    { monster: 'behir'},
    { monster: 'archmage', chance: 0.02},
    { monster: 'storm-giant'},
    { monster: 'vampire-bat'},
    { monster: 'vampire-mist'},
    { monster: 'vampire-vampire', chance: 0.02},
    { monster: 'mummy-lord'},
    { monster: 'purple-worm', chance: 0.02},
  ]),
  elemental: new Set([
   { monster: 'air-elemental'},
   { monster: 'earth-elemental'},
   { monster: 'fire-elemental'},
   { monster: 'salamander'},
   { monster: 'gargoyle'},
   { monster: 'water-elemental'},
   { monster: 'xorn'},
   { monster: 'invisible-stalker'},
   { monster: 'djinni'},
   { monster: 'efreeti'}
  ]),
  werefolk: new Set([
   { monster: 'wererat-rat'},
   { monster: 'weretiger-human'},
   { monster: 'werebear-human'},
   { monster: 'werewolf-wolf'},
   { monster: 'wereboar-human'},
   { monster: 'wereboar-boar'},
   { monster: 'wererat-hybrid'},
   { monster: 'werewolf-hybrid'},
   { monster: 'werebear-bear'},
   { monster: 'weretiger-tiger'}
  ]),
  monstrosity: new Set([
   { monster: 'bulette'},
   { monster: 'gorgon'},
   { monster: 'roper'},
   { monster: 'drider'},
   { monster: 'medusa'},
   { monster: 'chimera'},
   { monster: 'remorhaz'},
   { monster: 'roc'},
   { monster: 'spirit-naga'},
   { monster: 'hydra'}
  ])
}

module.exports = { allowedMonstersByPack }
