// shopMonsters.js

const allowedMonstersByPack = {
  starter: new Set([
    'darkmantle',
    'dryad',
    'ghoul',
  ]),
  common: new Set([
    'darkmantle',
    'homunculus',
    'dust-mephit',
    'magma-mephit',
    'flying-sword',
    'gnoll',
    'lemure',
    'manes',
    'harpy',
    'dryad',
    'violet-fungus',
    'ghoul',
    // 'ogre',
    'gibbering-mouther',
    // 'minotaur-skeleton',
    // 'basilisk',
    // 'green-hag',
    // 'werewolf-hybrid',
    // 'lamia',
    // 'couatl',
    // 'wereboar-hybrid',
  ]),
  uncommon: new Set([
    'roper',
    'red-slaad',
    'wraith',
    'hill-giant',
    'unicorn',
    'shambling-mound',
    'drider',
    'vrock',
    'mage',
    'chimera',
    'invisible-stalker',
    'mammoth',
    'bulette',
    'wyvern',
    'tyrannosaurus-rex',
    // 'oni',
    // 'shield-guardian',
    // 'giant-ape',
    // 'hydra',
    // 'cloaker',
    // 'assassin',
    // 'fire-giant',
    // 'clay-golem',
    // 'treant',
    // 'guardian-naga',
    // 'aboleth',
    // 'deva',
  ]),
  rare: new Set([
    'gynosphinx',
    'remorhaz',
    'efreeti',
    'archmage',
    'erinyes',
    'rakshasa',
    'storm-giant',
    'vampire',
    // 'purple-worm',
    // 'mummy-lord',
    // 'ice-devil',
  ]),
}

module.exports = { allowedMonstersByPack }
